# Generated by Django 3.0.3 on 2020-09-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumnx', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('pais', models.CharField(blank=True, max_length=20, null=True, verbose_name='País')),
                ('bio', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_inscripcion', models.DateField(auto_now=True, verbose_name='Fecha de inscripción')),
                ('img_pago', models.ImageField(blank=True, null=True, upload_to='pagos', verbose_name='Imagen pago')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('clave', models.CharField(blank=True, max_length=20, null=True, verbose_name='Clave')),
            ],
            options={
                'verbose_name': 'Alumnx',
                'verbose_name_plural': 'Alumnx',
            },
        ),
    ]
