# Generated by Django 3.0.3 on 2020-09-11 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_auto_20200911_0016'),
        ('alumno', '0002_alumno_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='numero_g',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='curso.Curso'),
        ),
    ]
