# Generated by Django 3.0.3 on 2020-09-11 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_auto_20200911_0101'),
        ('alumno', '0003_alumno_numero_g'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='numero_g',
        ),
        migrations.AddField(
            model_name='alumno',
            name='generacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='curso.Generacion'),
        ),
    ]
