# Generated by Django 3.0.3 on 2020-09-16 02:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0004_auto_20200911_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_inscripcion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de inscripción'),
        ),
    ]
