# Generated by Django 3.0.3 on 2020-09-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20200910_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='curso',
            name='nombre_curso',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
