# Generated by Django 3.0.3 on 2020-09-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_auto_20200911_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generacion',
            options={'verbose_name': 'Generación', 'verbose_name_plural': 'Generación'},
        ),
    ]
